//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.Integration.Books {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Books.IBooks")]
    public interface IBooks {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBooks/GetAll", ReplyAction="http://tempuri.org/IBooks/GetAllResponse")]
        Bookstore.Api.Model.Book[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBooks/GetAll", ReplyAction="http://tempuri.org/IBooks/GetAllResponse")]
        System.Threading.Tasks.Task<Bookstore.Api.Model.Book[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBooksChannel : Bookstore.Integration.Books.IBooks, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BooksClient : System.ServiceModel.ClientBase<Bookstore.Integration.Books.IBooks>, Bookstore.Integration.Books.IBooks {
        
        public BooksClient() {
        }
        
        public BooksClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BooksClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BooksClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BooksClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Bookstore.Api.Model.Book[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Bookstore.Api.Model.Book[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
